-- Junction table for best list content items and products
CREATE TABLE cp_best_list_products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_item_id BIGINT NOT NULL REFERENCES cp_content_items(id) ON DELETE CASCADE,
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  position INTEGER NOT NULL DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(content_item_id, product_id)
);

-- Index for efficient lookups
CREATE INDEX idx_best_list_products_content_item ON cp_best_list_products(content_item_id);
CREATE INDEX idx_best_list_products_product ON cp_best_list_products(product_id);

-- Updated_at trigger
CREATE TRIGGER on_cp_best_list_products_updated
  BEFORE UPDATE ON cp_best_list_products
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_updated_at();

-- RLS policies
ALTER TABLE cp_best_list_products ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to view best list products
CREATE POLICY "Users can view best list products"
  ON cp_best_list_products
  FOR SELECT
  TO authenticated
  USING (true);

-- Allow users with content roles to manage best list products
CREATE POLICY "Content managers can manage best list products"
  ON cp_best_list_products
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM user_roles
      WHERE user_roles.user_id = auth.uid()
      AND user_roles.role IN ('admin', 'editor', 'author')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM user_roles
      WHERE user_roles.user_id = auth.uid()
      AND user_roles.role IN ('admin', 'editor', 'author')
    )
  );
